// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    AppBtnCircle: typeof import('./src/components/App/AppBtnCircle.vue')['default']
    AppContact: typeof import('./src/components/App/AppContact.vue')['default']
    AppFooter: typeof import('./src/components/App/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/App/AppHeader.vue')['default']
    AppHeaderLink: typeof import('./src/components/App/AppHeaderLink.vue')['default']
    AppHeaderLinkSection: typeof import('./src/components/App/AppHeaderLinkSection.vue')['default']
    AppLanguage: typeof import('./src/components/App/AppLanguage.vue')['default']
    AppSectionTitle: typeof import('./src/components/App/AppSectionTitle.vue')['default']
    AppSelect: typeof import('./src/components/App/AppSelect.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    IFluentGlobeDesktop20Filled: typeof import('~icons/fluent/globe-desktop20-filled')['default']
    IIcRoundSwipeUp: typeof import('~icons/ic/round-swipe-up')['default']
    IPhArrowUpRight: typeof import('~icons/ph/arrow-up-right')['default']
    IPhCaretDown: typeof import('~icons/ph/caret-down')['default']
    IPhCaretLeft: typeof import('~icons/ph/caret-left')['default']
    IPhCaretRight: typeof import('~icons/ph/caret-right')['default']
    IPhCloudFill: typeof import('~icons/ph/cloud-fill')['default']
    IPhGithubLogoFill: typeof import('~icons/ph/github-logo-fill')['default']
    IPhLink: typeof import('~icons/ph/link')['default']
    IPhListFill: typeof import('~icons/ph/list-fill')['default']
    IPhPencilCircleFill: typeof import('~icons/ph/pencil-circle-fill')['default']
    IPhRulerFill: typeof import('~icons/ph/ruler-fill')['default']
    IPhXFill: typeof import('~icons/ph/x-fill')['default']
    IRiInstagramFill: typeof import('~icons/ri/instagram-fill')['default']
    ITablerLanguage: typeof import('~icons/tabler/language')['default']
    Services: typeof import('./src/components/Services.vue')['default']
    ServicesCard: typeof import('./src/components/ServicesCard.vue')['default']
    Works: typeof import('./src/components/Works.vue')['default']
    WorksSlider: typeof import('./src/components/WorksSlider.vue')['default']
  }
}
